# Architecture reconstruction
import keras
import sys
sys.path.append('../')
from ..quantize_layers import Conv2D_Q, Dense_Q, DepthwiseConv2D_Q
def AlexNet(kq=None,
		bq=None,
		aq=None,
		activation=None,
		after_activation=None):
	inputs=keras.layers.Input(shape=(224,224,3))
	x=Conv2D_Q(name='conv2d_9',
		trainable=True,
		batch_input_shape=(None, 224, 224, 3),
		dtype='float32',
		filters=96,
		kernel_size=(11, 11),
		strides=(4, 4),
		padding='valid',
		data_format='channels_last',
		dilation_rate=(1, 1),
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(inputs)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_11',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	x=keras.layers.pooling.MaxPooling2D(name='max_pooling2d_6',
		trainable=True,
		pool_size=(3, 3),
		padding='valid',
		strides=(2, 2),
		data_format='channels_last')(x)
	x=Conv2D_Q(name='conv2d_10',
		trainable=True,
		filters=256,
		kernel_size=(5, 5),
		strides=(1, 1),
		padding='same',
		data_format='channels_last',
		dilation_rate=(1, 1),
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(x)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_12',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	x=keras.layers.pooling.MaxPooling2D(name='max_pooling2d_7',
		trainable=True,
		pool_size=(3, 3),
		padding='valid',
		strides=(2, 2),
		data_format='channels_last')(x)
	x=Conv2D_Q(name='conv2d_11',
		trainable=True,
		filters=384,
		kernel_size=(3, 3),
		strides=(1, 1),
		padding='same',
		data_format='channels_last',
		dilation_rate=(1, 1),
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(x)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_13',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	x=Conv2D_Q(name='conv2d_12',
		trainable=True,
		filters=384,
		kernel_size=(3, 3),
		strides=(1, 1),
		padding='same',
		data_format='channels_last',
		dilation_rate=(1, 1),
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(x)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_14',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	x=Conv2D_Q(name='conv2d_13',
		trainable=True,
		filters=256,
		kernel_size=(3, 3),
		strides=(1, 1),
		padding='same',
		data_format='channels_last',
		dilation_rate=(1, 1),
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(x)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_15',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	x=keras.layers.pooling.MaxPooling2D(name='max_pooling2d_8',
		trainable=True,
		pool_size=(3, 3),
		padding='valid',
		strides=(2, 2),
		data_format='channels_last')(x)
	x=keras.layers.core.Flatten(name='flatten_3',
		trainable=True,
		data_format='channels_last')(x)
	x=Dense_Q(name='dense_5',
		trainable=True,
		units=4096,
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(x)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_16',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	x=keras.layers.core.Dropout(name='dropout_5',
		trainable=True,
		rate=0.5,
		noise_shape=None,
		seed=None)(x)
	x=Dense_Q(name='dense_6',
		trainable=True,
		units=4096,
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(x)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_17',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	x=keras.layers.core.Dropout(name='dropout_6',
		trainable=True,
		rate=0.5,
		noise_shape=None,
		seed=None)(x)
	outputs=Dense_Q(name='dense_7',
		trainable=True,
		units=1000,
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(x)
	model=keras.models.Model(inputs,outputs)
	return model