# Architecture reconstruction
import keras
import sys
sys.path.append('../')
from ..quantize_layers import Conv2D_Q, Dense_Q, DepthwiseConv2D_Q
def LeNet5(kq=None,
		bq=None,
		aq=None,
		activation=None,
		after_activation=None):
	inputs=keras.layers.Input(shape=(28,28,1))
	x=Conv2D_Q(name='conv2d_1',
		trainable=True,
		batch_input_shape=(None, 28, 28, 1),
		dtype='float32',
		filters=32,
		kernel_size=(5, 5),
		strides=(1, 1),
		padding='same',
		data_format='channels_last',
		dilation_rate=(1, 1),
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(inputs)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_1',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	x=keras.layers.pooling.MaxPooling2D(name='max_pooling2d_1',
		trainable=True,
		pool_size=(2, 2),
		padding='valid',
		strides=(2, 2),
		data_format='channels_last')(x)
	x=Conv2D_Q(name='conv2d_2',
		trainable=True,
		filters=64,
		kernel_size=(5, 5),
		strides=(1, 1),
		padding='same',
		data_format='channels_last',
		dilation_rate=(1, 1),
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(x)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_2',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	x=keras.layers.pooling.MaxPooling2D(name='max_pooling2d_2',
		trainable=True,
		pool_size=(2, 2),
		padding='valid',
		strides=(2, 2),
		data_format='channels_last')(x)
	x=keras.layers.core.Flatten(name='flatten_1',
		trainable=True,
		data_format='channels_last')(x)
	x=Dense_Q(name='dense_1',
		trainable=True,
		units=512,
		activation=activation,
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq,
		aq=aq,
		after_activation=after_activation)(x)
	x=keras.layers.normalization.BatchNormalization(name='batch_normalization_3',
		trainable=True,
		axis=-1,
		momentum=0.99,
		epsilon=0.001,
		center=True,
		scale=True,
		beta_initializer={'class_name': 'Zeros', 'config': {}},
		gamma_initializer={'class_name': 'Ones', 'config': {}},
		moving_mean_initializer={'class_name': 'Zeros', 'config': {}},
		moving_variance_initializer={'class_name': 'Ones', 'config': {}},
		beta_regularizer=None,
		gamma_regularizer=None,
		beta_constraint=None,
		gamma_constraint=None)(x)
	outputs=Dense_Q(name='dense_2',
		trainable=True,
		units=10,
		activation="softmax",
		use_bias=True,
		kernel_regularizer=None,
		bias_regularizer=None,
		activity_regularizer=None,
		kernel_constraint=None,
		bias_constraint=None,
		kq=kq,
		bq=bq)(x)
	model=keras.models.Model(inputs,outputs)
	return model
